''' Resource locations '''

APP_URL = 'https://app.musicleague.com'
GITHUB_URL = 'https://api.github.com'
SPOTIFY_PLAY_URL = 'https://open.spotify.com'
SPOTIFY_AUTH_URL = 'https://accounts.spotify.com'
MOSAIC_URL = 'https://mosaic.scdn.co'
LASTFM_URL = 'http://ws.audioscrobbler.com'
WIKI_URL = 'https://en.wikipedia.org'
BITIO_URL = 'https://api.bit.io'
BITIO_HOST = 'db.bit.io'