# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: PAWS - Update Results

on:
#  push:
#    branches: [ main ]
#  pull_request:
#    branches: [ main ]
  schedule:
    - cron: '0 * * * *'

jobs:

  build:

    runs-on: ubuntu-latest
    
    environment: playpaws

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    #- name: Lint with flake8
    #  run: |
    #    # stop the build if there are Python syntax errors or undefined names
    #    flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
    #    # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
    #    flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    #- name: Test with pytest
    #  run: |
    #    pytest
    - name: Update database and outputs      
      env:
        BITIO_DBNAME: ${{ secrets.BITIO_DBNAME }}
        BITIO_PASSWORD: ${{ secrets.BITIO_PASSWORD }}
        BITIO_USERNAME: ${{ secrets.BITIO_USERNAME }}

        DROPBOX_APP_KEY: ${{ secrets.DROPBOX_APP_KEY }}
        DROPBOX_APP_SECRET: ${{ secrets.DROPBOX_APP_SECRET }}
        DROPBOX_TOKEN: ${{ secrets.DROPBOX_TOKEN }}

        LASTFM_API_KEY: ${{ secrets.LASTFM_API_KEY }}
        LASTFM_API_SECRET: ${{ secrets.LASTFM_API_SECRET }}

        SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
        SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
        SPOTIFY_REDIRECT_URL: ${{ secrets.SPOTIFY_REDIRECT_URL }}
        SPOTIFY_USER_ID: ${{ secrets.SPOTIFY_USER_ID }}
        SPOTIFY_REFRESH_TOKEN: ${{ secrets.SPOTIFY_REFRESH_TOKEN }}

        GCP_API_KEY: ${{ secrets.GCP_API_KEY }}
        GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
        GCP_PROJECT_CX: ${{ secrets.GCP_PROJECT_CX }}

        GCP_I_API_KEY: ${{ secrets.GCP_I_API_KEY }}
        GCP_I_PROJECT_ID: ${{ secrets.GCP_I_PROJECT_ID }}
        GCP_I_PROJECT_CX: ${{ secrets.GCP_I_PROJECT_CX }}

        GCP_M_CLIENT_ID: ${{ secrets.GCP_M_CLIENT_ID }}
        GCP_M_CLIENT_SECRET: ${{ secrets.GCP_M_CLIENT_SECRET }}
        GCP_M_REFRESH_TOKEN: ${{ secrets.GCP_M_REFRESH_TOKEN }}

        GCP_S_PROJECT_ID: ${{ secrets.GCP_S_PROJECT_ID }}
        GCP_S_ACCOUNT_NAME: ${{ secrets.GCP_S_ACCOUNT_NAME }}
        GCP_S_PRIVATE_KEY_ID: ${{ secrets.GCP_S_PRIVATE_KEY_ID }}
        GCP_S_PRIVATE_KEY: ${{ secrets.GCP_S_PRIVATE_KEY }}
        GCP_S_CLIENT_ID: ${{ secrets.GCP_S_CLIENT_ID }}

        ML_COOKIE_NAME: ${{ secrets.ML_COOKIE_NAME }}
        ML_COOKIE_VALUE: ${{ secrets.ML_COOKIE_VALUE }}
      run: |
        python paws.py
