# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    #- name: Test with pytest
    #  run: |
    #    pytest
    - name: Update database and outputs
      run: |
        python paws.py
      env: |
        BITIO_ADD_ON: _demo_db_connection
        BITIO_DBNAME: playpaws
        BITIO_HOST: db.bit.io
        BITIO_LANGUAGE: postgres
        BITIO_PASSWORD: EU9q_Dgmc59F49eCXAe4BnpTWi8h
        BITIO_STRING: postgresql://mfranzonello_demo_db_connection:EU9q_Dgmc59F49eCXAe4BnpTWi8h@db.bit.io
        BITIO_USERNAME: mfranzonello

        DROPBOX_APP_KEY: dx4rsb5bpgjm3lu
        DROPBOX_APP_SECRET: 33dn35jmiu3li46
        DROPBOX_TOKEN: SgWh-ldV-HQAAAAAAAAAAVCMjQ9XDrUNBqhKSOo22UEsznuK9yUJhacskfvWwyOU

        LASTFM_API_KEY: 28d70ef54ef9ce25de073115f8045a32
        LASTFM_API_SECRET: 692c47c2808300ee580ccc3e49ca0e71

        SPOTIFY_CLIENT_ID: a8c5b3817f40406680b7dc4b83312f15
        SPOTIFY_CLIENT_SECRET: d98449bd5c9540acb1dd9d983aba8522
        SPOTIFY_REDIRECT_URL: http://localhost:8888/callback
        SPOTIFY_USER_ID: 12125687151

        GCP_API_KEY: AIzaSyBlGoIZ0YcbHJEFWGAjp6pJ29gHnQaGwgw
        GCP_PROJECT_ID: 348372420583
        GCP_PROJECT_CX: 812b2523e448aa38a

        ML_COOKIE_NAME: session
        ML_COOKIE_VALUE: .eJw9kMtuqzAARP-FdZAA8-zOPBMngNMmomWDjDGBUF4GEprq_vtl1fWMjs7Mr5ANjLekY90svM18YTuBUMqmKZv7hnXCm2Cfob_aHL8szX6qia3cyHl8Fs7jYb5fpDK8DoZ6n24NBdEAr4klf4qfe4Rn5GB-KEY8LZWzxlkcVu0LHr6wtywHgr6PaY9oYFQSTfBgj0qPqnE2j_VpEVHm-ahWoN9nep7aPyfLJfGz8VLYyrbu7sHFu1JhJ9CF8807WybGN1FZAZpq6ZIEtoytQ83ZlJFtlqwDFaiypZg7oS62Zp4DkpukFCWqa6JaloaYy4yIpqEAiVLFLAp1Y3BWbojq7wl4hvh4k2BSuWFQg9vJcNNIVzMzcGc37JoISNdm2petP2jvzqi2RHOZladu-eije3V8-RGKZxSSICDV2YOG8eElKL7Pq4iVH54Ul2ftrRZxxO_CzHHHpoEfUt6Z2PNH6H0oWij8-w_qOYtC.YWoGJw.fSoKiY3d2sxISpIznQCsN027Ni4
