# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: REPEAT - Deadline Extension

on:
#  push:
#    branches: [ main ]
#  pull_request:
#    branches: [ main ]
  schedule:
    - cron: '0 12 * * *'

jobs:

  build:

    runs-on: ubuntu-latest
    
    environment: playpaws

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements-lite.txt ]; then pip install -r requirements-lite.txt; fi
    #- name: Lint with flake8
    #  run: |
    #    # stop the build if there are Python syntax errors or undefined names
    #    flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
    #    # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
    #    flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    #- name: Test with pytest
    #  run: |
    #    pytest
    - name: Extend deadlines automatically      
      env:
        BITIO_ADD_ON: ${{ secrets.BITIO_ADD_ON }}
        BITIO_DBNAME: ${{ secrets.BITIO_DBNAME }}
        BITIO_HOST: ${{ secrets.BITIO_HOST }}
        BITIO_LANGUAGE: ${{ secrets.BITO_LANGUAGE }}
        BITIO_PASSWORD: ${{ secrets.BITIO_PASSWORD }}
        BITIO_STRING: ${{ secrets.BITIO_STRING }}
        BITIO_USERNAME: ${{ secrets.BITIO_USERNAME }}

        ML_COOKIE_NAME: ${{ secrets.ML_COOKIE_NAME }}
        ML_COOKIE_VALUE: ${{ secrets.ML_COOKIE_VALUE }}
      run: |
        python repeat.py
